baseURL = 'https://visimp.teapot.ovh'
languageCode = 'en-us'
theme = "hugo-book"
title = 'visimp'

enableGitInfo = true

[markup]
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'gruvbox'
    tabWidth = 2

[menu]
[[menu.after]]
  name = "Source"
  url = "https://github.com/visimp"
  weight = 10

[params]
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main'
  BookTheme = 'auto'
  BookRepo = 'https://github.com/visimp/pages'
