name: Spellcheck
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: typos-action
        uses: crate-ci/typos@v1.36.3
